export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS";
export const FETCH_ALL_FORUMS = "FETCH_ALL_FORUMS";
export const FETCH_ALL_NOTIFICATIONS = "FETCH_ALL_NOTIFICATIONS";